name: kaggle-digit-recognizer
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - kaggle
  - pip
  - pip:
    - tensorflow==2.0.0-alpha0
    - sklearn